import type { Project, BlogPost } from "./types"

export const projects: Project[] = [
  {
    id: "mobile-banking-app",
    title: "Mobile Banking App",
    description: "A modern mobile banking application with a focus on user experience and security.",
    image: "/placeholder.svg?height=400&width=600",
    client: "FinTech Inc.",
    timeline: "3 months",
    role: "Lead UI/UX Designer",
    tools: ["Figma", "Sketch", "Principle"],
    link: "https://example.com/project1",
  },
  {
    id: "e-commerce-website",
    title: "E-Commerce Website",
    description: "A responsive e-commerce platform with an intuitive shopping experience.",
    image: "/placeholder.svg?height=400&width=600",
    client: "Shop & Co.",
    timeline: "4 months",
    role: "UI Designer",
    tools: ["Adobe XD", "Illustrator", "InVision"],
  },
  {
    id: "health-tracking-app",
    title: "Health Tracking App",
    description: "A health and fitness tracking application with personalized insights.",
    image: "/placeholder.svg?height=400&width=600",
    client: "HealthTech",
    timeline: "2 months",
    role: "UX Designer",
    tools: ["Figma", "Framer", "Miro"],
    link: "https://example.com/project3",
  },
  {
    id: "travel-booking-platform",
    title: "Travel Booking Platform",
    description: "A comprehensive travel booking platform with a seamless booking experience.",
    image: "/placeholder.svg?height=400&width=600",
    client: "TravelEase",
    timeline: "5 months",
    role: "Lead Designer",
    tools: ["Figma", "Adobe XD", "Protopie"],
  },
  {
    id: "productivity-dashboard",
    title: "Productivity Dashboard",
    description: "A productivity dashboard for teams to track progress and manage tasks.",
    image: "/placeholder.svg?height=400&width=600",
    client: "WorkSmart",
    timeline: "3 months",
    role: "UI/UX Designer",
    tools: ["Sketch", "InVision", "Zeplin"],
    link: "https://example.com/project5",
  },
  {
    id: "social-media-app",
    title: "Social Media App",
    description: "A social media application focused on community building and content sharing.",
    image: "/placeholder.svg?height=400&width=600",
    client: "ConnectHub",
    timeline: "6 months",
    role: "Product Designer",
    tools: ["Figma", "After Effects", "Principle"],
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Power of Design Systems",
    slug: "design-systems",
    excerpt: "How design systems can transform your product development process.",
    content: "Full content of the blog post...",
    image: "/placeholder.svg?height=400&width=600",
    date: "April 1, 2023",
    readTime: 5,
  },
  {
    id: "2",
    title: "UX Research Techniques",
    slug: "ux-research",
    excerpt: "A guide to the most effective user research methods for designers.",
    content: "Full content of the blog post...",
    image: "/placeholder.svg?height=400&width=600",
    date: "March 15, 2023",
    readTime: 8,
  },
  {
    id: "3",
    title: "Designing for Accessibility",
    slug: "accessibility",
    excerpt: "Why accessible design is good design and how to implement it.",
    content: "Full content of the blog post...",
    image: "/placeholder.svg?height=400&width=600",
    date: "February 28, 2023",
    readTime: 6,
  },
  {
    id: "4",
    title: "The Future of UI Animation",
    slug: "ui-animation",
    excerpt: "Exploring the latest trends in UI animation and motion design.",
    content: "Full content of the blog post...",
    image: "/placeholder.svg?height=400&width=600",
    date: "February 15, 2023",
    readTime: 4,
  },
  {
    id: "5",
    title: "Color Theory for Digital Designers",
    slug: "color-theory",
    excerpt: "Understanding color theory and its application in digital design.",
    content: "Full content of the blog post...",
    image: "/placeholder.svg?height=400&width=600",
    date: "January 30, 2023",
    readTime: 7,
  },
  {
    id: "6",
    title: "Designing for Dark Mode",
    slug: "dark-mode",
    excerpt: "Best practices for creating effective dark mode experiences.",
    content: "Full content of the blog post...",
    image: "/placeholder.svg?height=400&width=600",
    date: "January 15, 2023",
    readTime: 5,
  },
]

